[package]
name = "my-redis"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mini-redis = "0.4.1"
tokio = { version = "1.11.0", features = ["full"] }
